/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    // Include source JS/TSX and CSS files so utilities referenced in CSS (@apply)
    // are detected by the scanner and generated by Tailwind.
    "./src/**/*.{js,ts,jsx,tsx,css}",
    "./src/**/*.css",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#3b82f6',
          hover: '#2563eb',
        },
        secondary: '#6b7280',
      },
      spacing: {
        'section': '2rem',
        'container': '1rem',
      },
      borderRadius: {
        'container': '0.5rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  // Safelist utilities referenced only inside CSS via @apply so the
  // v4 scanner emits them. This is a pragmatic migration step; you can
  // later replace @apply usages with utility classes in markup.
  safelist: [
    { pattern: /^text-/ },
    { pattern: /^bg-/ },
    { pattern: /^border/ },
    { pattern: /^focus/ },
    { pattern: /^hover/ },
    { pattern: /^disabled/ },
    { pattern: /^px-/ },
    { pattern: /^py-/ },
    { pattern: /^w-/ },
    { pattern: /^rounded/ },
    { pattern: /^shadow/ },
    { pattern: /^transition/ },
    { pattern: /^font-/ },
    { pattern: /^outline/ },
    { pattern: /^animate-/ },
  ],
  plugins: [],
}
