"""Add exercise library tables

Revision ID: 3b122e6b3ede
Revises: 68b8821e890c
Create Date: 2025-09-27 17:13:27.764990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b122e6b3ede'
down_revision = '68b8821e890c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('movement_category', sa.Enum('STRENGTH', 'POWER', 'ENDURANCE', 'MOBILITY', 'BALANCE', 'COORDINATION', name='movementcategory'), nullable=False),
    sa.Column('exercise_classification', sa.Enum('COMPOUND', 'ISOLATION', 'ACCESSORY', 'OLYMPIC', 'PLYOMETRIC', name='exerciseclassification'), nullable=False),
    sa.Column('muscle_involvement', sa.JSON(), nullable=True),
    sa.Column('primary_adaptations', sa.JSON(), nullable=True),
    sa.Column('secondary_adaptations', sa.JSON(), nullable=True),
    sa.Column('demands', sa.JSON(), nullable=True),
    sa.Column('primary_equipment', sa.Enum('BODYWEIGHT', 'FREE_WEIGHTS', 'MINIMAL_EQUIPMENT', 'FULL_GYM', 'BARBELL', 'DUMBBELLS', 'KETTLEBELLS', 'RESISTANCE_BANDS', 'PULL_UP_BAR', 'SUSPENSION_TRAINER', 'MEDICINE_BALL', 'CABLE_MACHINE', 'MACHINES', name='equipment'), nullable=False),
    sa.Column('alternative_equipment', sa.JSON(), nullable=True),
    sa.Column('technique_complexity', sa.Integer(), nullable=False),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('setup_instructions', sa.Text(), nullable=True),
    sa.Column('execution_cues', sa.JSON(), nullable=True),
    sa.Column('common_mistakes', sa.JSON(), nullable=True),
    sa.Column('safety_notes', sa.JSON(), nullable=True),
    sa.Column('progressions', sa.JSON(), nullable=True),
    sa.Column('regressions', sa.JSON(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('demonstration_url', sa.String(), nullable=True),
    sa.Column('form_video_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_exercises_movement_category', 'exercises', ['movement_category'], unique=False)
    op.create_index('ix_exercises_movement_category_classification', 'exercises', ['movement_category', 'exercise_classification'], unique=False)
    op.create_index('ix_exercises_primary_equipment', 'exercises', ['primary_equipment'], unique=False)
    op.create_table('user_exercise_data',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('personal_records', sa.JSON(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('form_mastery_level', sa.Integer(), nullable=False),
    sa.Column('user_contraindications', sa.JSON(), nullable=True),
    sa.Column('preferred_modifications', sa.JSON(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('last_performed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progression_trend', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'exercise_id')
    )
    op.create_table('workout_phases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workout_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase_type', sa.Enum('WARMUP', 'MAIN', 'ACCESSORY', 'COOLDOWN', name='workoutphasetype'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'position', name='uq_workout_phase_position')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phase_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.JSON(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('load', sa.JSON(), nullable=False),
    sa.Column('tempo', sa.String(), nullable=True),
    sa.Column('rpe_target', sa.Integer(), nullable=True),
    sa.Column('superset_group', sa.String(), nullable=True),
    sa.Column('coaching_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['workout_phases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_id', 'position', name='uq_phase_position')
    )
    op.create_index('ix_workout_exercises_exercise_id', 'workout_exercises', ['exercise_id'], unique=False)
    op.create_index('ix_workout_exercises_phase_id', 'workout_exercises', ['phase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workout_exercises_phase_id', table_name='workout_exercises')
    op.drop_index('ix_workout_exercises_exercise_id', table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_table('workout_phases')
    op.drop_table('user_exercise_data')
    op.drop_index('ix_exercises_primary_equipment', table_name='exercises')
    op.drop_index('ix_exercises_movement_category_classification', table_name='exercises')
    op.drop_index('ix_exercises_movement_category', table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
