"""Create daily state and recommendation models

Revision ID: 68b8821e890c
Revises: 899b901afe4a
Create Date: 2025-09-27 15:35:17.696158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b8821e890c'
down_revision = '899b901afe4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contextual_recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('SESSION_MODIFICATION', 'WELLNESS_ACTION', 'MOTIVATIONAL', 'EDUCATIONAL', name='recommendationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='recommendationpriority'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('user_response', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_priority_created_at', 'contextual_recommendations', ['priority', 'created_at'], unique=False)
    op.create_index('ix_recommendations_user_id_expires_at', 'contextual_recommendations', ['user_id', 'expires_at'], unique=False)
    op.create_table('daily_states',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('scheduled_session', sa.JSON(), nullable=True),
    sa.Column('daily_priorities', sa.JSON(), nullable=True),
    sa.Column('relevant_progress', sa.JSON(), nullable=True),
    sa.Column('available_actions', sa.JSON(), nullable=True),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_index('ix_daily_states_user_id_expires_at', 'daily_states', ['user_id', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_states_user_id_expires_at', table_name='daily_states')
    op.drop_table('daily_states')
    op.drop_index('ix_recommendations_user_id_expires_at', table_name='contextual_recommendations')
    op.drop_index('ix_recommendations_priority_created_at', table_name='contextual_recommendations')
    op.drop_table('contextual_recommendations')
    # ### end Alembic commands ###
