"""Create program and AI models

Revision ID: 899b901afe4a
Revises:
Create Date: 2025-09-27 15:24:48.495164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899b901afe4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_contexts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_preferences', sa.JSON(), nullable=True),
    sa.Column('patterns', sa.JSON(), nullable=True),
    sa.Column('current_state', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('program_type', sa.Enum('AI_GENERATED', 'USER_CREATED', 'TEMPLATE', 'HYBRID', name='programtype'), nullable=False),
    sa.Column('created_by', sa.Enum('AI', 'USER', 'TEMPLATE', name='createdby'), nullable=False),
    sa.Column('goal_analysis', sa.JSON(), nullable=True),
    sa.Column('total_duration_weeks', sa.Integer(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('training_frequency', sa.Integer(), nullable=False),
    sa.Column('session_duration_target', sa.Integer(), nullable=False),
    sa.Column('adaptation_history', sa.JSON(), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('user_satisfaction_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='programstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_programs_created_at', 'programs', ['created_at'], unique=False)
    op.create_index('ix_programs_user_id_status', 'programs', ['user_id', 'status'], unique=False)
    op.create_table('program_adaptations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('program_id', sa.String(), nullable=False),
    sa.Column('adaptation_type', sa.Enum('AI_AUTOMATIC', 'USER_REQUESTED', 'WELLNESS_TRIGGERED', 'PERFORMANCE_TRIGGERED', name='adaptationtype'), nullable=False),
    sa.Column('trigger_data', sa.JSON(), nullable=False),
    sa.Column('changes_made', sa.JSON(), nullable=False),
    sa.Column('effectiveness_tracking', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_cycles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('program_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cycle_order', sa.Integer(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('cycle_focus', sa.Enum('ANATOMICAL_ADAPTATION', 'STRENGTH_BUILDING', 'HYPERTROPHY_EMPHASIS', 'STRENGTH_PEAKING', name='cyclefocus'), nullable=False),
    sa.Column('volume_emphasis', sa.Enum('LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', name='volumeemphasis'), nullable=False),
    sa.Column('intensity_progression', sa.Enum('LINEAR', 'UNDULATING', 'AUTO_REGULATED', name='intensityprogression'), nullable=False),
    sa.Column('adaptation_triggers', sa.JSON(), nullable=True),
    sa.Column('success_criteria', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'cycle_order', name='uq_program_cycle_order')
    )
    op.create_table('workouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cycle_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workout_type', sa.Enum('STRENGTH_FOCUSED', 'HYPERTROPHY_FOCUSED', 'CARDIO_INTERVALS', 'MOBILITY_FOCUSED', name='workouttype'), nullable=False),
    sa.Column('training_style', sa.Enum('TRADITIONAL_SETS', 'SUPERSET', 'CIRCUIT', 'REST_PAUSE', name='trainingstyle'), nullable=False),
    sa.Column('estimated_duration', sa.JSON(), nullable=False),
    sa.Column('equipment_required', sa.Enum('BODYWEIGHT', 'FREE_WEIGHTS', 'MINIMAL_EQUIPMENT', 'FULL_GYM', name='equipmentrequired'), nullable=False),
    sa.Column('adaptation_flexibility', sa.Enum('RIGID', 'MODERATE', 'HIGH', name='adaptationflexibility'), nullable=False),
    sa.Column('auto_progression_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['training_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workouts')
    op.drop_table('training_cycles')
    op.drop_table('program_adaptations')
    op.drop_index('ix_programs_user_id_status', table_name='programs')
    op.drop_index('ix_programs_created_at', table_name='programs')
    op.drop_table('programs')
    op.drop_table('ai_contexts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
